spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:weatherDb
  h2:
    console:
      enabled: true
  config:
    import: optional:file:.env[.properties]

server:
  port: 9999


weather-stack:
  api-url: http://api.weatherstack.com/current
  api-key: ${API_KEY:6cb7539e1a6509ea4fc2b6d637a540fe}


resilience4j:
  ratelimiter:
    instances:
      basic:
        limit-for-period: 10
        limit-refresh-period: 1m
        timeout-duration: 10s

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
          - prometheus

